apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Geboyi/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  # helm:
  #   valueFiles:
  #     - values.yaml
  # ksonnet:
  #   environment: default
  #   component: my-component
  # kustomize:
  #   images:
  #     - name: my-image
  #       newTag: latest
  # plugin:
  #   name: plugin-name
  #   version: plugin-version
  # directory:
  #   recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: myapp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
        prune: true
        selfHeal: true
